name: Create or Update PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Lenra Component Version'
        required: true
      release_notes:
        description: 'Lenra Component Release notes'
        required: false
      origin:
        description: 'Label of the dependency to change version.'
        required: true

jobs:
  create_or_update_pr:
    name: Create or Update PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup yq
        id: setup-yq
        uses: shiipou/setup-yq-action@v2.0.1
      - name: create_pr
        uses: shiipou/workflows/create_or_update_pr@main
        with:
          name: 'Update dependecies'
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          script: |
            if [[ "${{ github.event.inputs.origin }}" == "components-api" ]]; then
              cd priv/components-api
              git fetch --all --tags
              git checkout "tags/${{ github.event.inputs.version }}"
              cd ../..
              git add priv/components-api
            else
              >&2 echo "Error: ${{ github.event.inputs.origin }} not yet implemented"
              exit 1
            fi
            
            RELEASE_NOTES="${{ github.event.inputs.release_notes }}"
            RELEASE_TYPE="${RELEASE_NOTES/:*}"
            
            git commit -m "${RELEASE_NOTES}: Upgrade ${{ github.event.inputs.origin }} to ${{ github.event.inputs.version }}
            ${{ github.event.inputs.release_notes }}"
